version: '3.4'

services:
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    network_mode: host
    privileged: true
    restart: unless-stopped
